env:
  global:
    - CC_TEST_REPORTER_ID=62c3cc32f27d201dd0c1b5bfa6f345a0d9c8caf2d98488eff43839b8d308c7cf
language: ruby
services:
  - mysql
cache:
  bundler: true
  apt: true
  directories:
    - "/home/travis/build/regic/rails5/coverage"
rvm:
  - 2.2.10
before_script:
  - mysql -e 'CREATE DATABASE bio_test;'
  - "cp .travis.database.yml ./config/database.yml"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

jobs:
  include:
    - stage: test
      script: bundle exec rspec && ./cc-test-reporter format-coverage -t simplecov -o /home/travis/build/regic/rails5/coverage/codeclimate.rspec.json
      deploy:
        provider: script
        script: pwd && ls -alFX && cd /home/travis/build/regic/rails5/coverage && ls -alFX
        on:
          all_branches: true
    - stage: test
      script: bundle exec cucumber && ./cc-test-reporter format-coverage -t simplecov -o /home/travis/build/regic/rails5/coverage/codeclimate.cucumber.json
      deploy:
        provider: script
        script: pwd && ls -alFX && cd /home/travis/build/regic/rails5/coverage && ls -alFX
        on:
          all_branches: true
