env:
  global:
    - CC_TEST_REPORTER_ID=62c3cc32f27d201dd0c1b5bfa6f345a0d9c8caf2d98488eff43839b8d308c7cf
language: ruby
services:
  - mysql
cache:
  bundler: true
  apt: true
rvm:
  - 2.2.10
before_script:
  - mysql -e 'CREATE DATABASE bio_test;'
  - "cp .travis.database.yml ./config/database.yml"
  - mkdir -p /tmp/coverage && curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/coverage/cc-test-reporter
  - chmod +x /tmp/coverage/cc-test-reporter
  - /tmp/coverage/cc-test-reporter before-build

jobs:
  allow_failures:
    - name: test
  include:
    - stage: test
      name: test
      script: bundle exec rspec && /tmp/coverage/cc-test-reporter format-coverage -t simplecov -o /tmp/coverage/codeclimate.rspec.json && if [ "$TRAVIS_TEST_RESULT" == 1 ]; then touch /tmp/coverage/fail; fi
      workspaces:
        create:
          name: rspec
          paths: /tmp/coverage
    - stage: test
      name: test
      script: bundle exec cucumber && /tmp/coverage/cc-test-reporter format-coverage -t simplecov -o /tmp/coverage/codeclimate.cucumber.json && if [ "$TRAVIS_TEST_RESULT" == 1 ]; then touch /tmp/coverage/fail; fi
      workspaces:
        create:
          name: cucumber
          paths: /tmp/coverage
    - stage: codeclimate
      name: codeclimate
      git:
        clone: false
      language: minimal
      install: skip
      before_script: skip
      script: skip
      services: skip
      workspaces:
        use:
          - rspec
          - cucumber
      script: cd /tmp/coverage && ./cc-test-reporter sum-coverage codeclimate.*.json -p 2 -o codeclimate.json && ./cc-test-reporter upload-coverage -i codeclimate.json && if [ -f /tmp/coverage/fail ]; then exit 1; fi
      # if: branch = master
