development:
  adapter: mysql2
  database: bio_test
  host: localhost
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

test: &TEST
  adapter: mysql2
  database: bio_test
  username: root
  password: password
  encoding: utf8

cucumber:
  <<: *TEST
